.define rVRamAddress $2116
.define rVRamDataWrite $2118

.define rNesControllerPort1 $4016
.define rNesControllerPort2 $4017

.define rDMATrigger $420B
.define rHDMATrigger $420C

.define rDMA0Config $4300
.define rDMA0Dest $4301
.define rDMA0SourceOffsetW $4302
.define rDMA0SourceBank $4304
.define rDMA0ByteCountW $4305

.define rDMA1Config $4310
.define rDMA1Dest $4311
.define rDMA1SourceOffsetW $4312
.define rDMA1SourceBank $4314
.define rDMA1ByteCountW $4315

.define rDMA2Config $4320
.define rDMA2Dest $4321
.define rDMA2SourceOffsetW $4322
.define rDMA2SourceBank $4324
.define rDMA2ByteCountW $4325

.define rDMA3Config $4330
.define rDMA3Dest $4331
.define rDMA3SourceOffsetW $4332
.define rDMA3SourceBank $4334
.define rDMA3ByteCountW $4335

.define rDMA4Config $4340
.define rDMA4Dest $4341
.define rDMA4SourceOffsetW $4342
.define rDMA4SourceBank $4344
.define rDMA4ByteCountW $4345

.define rDMA5Config $4350
.define rDMA5Dest $4351
.define rDMA5SourceOffsetW $4352
.define rDMA5SourceBank $4354
.define rDMA5ByteCountW $4355

.define rDMA6Config $4360
.define rDMA6Dest $4361
.define rDMA6SourceOffsetW $4362
.define rDMA6SourceBank $4364
.define rDMA6ByteCountW $4365

.define rDMA7Config $4370
.define rDMA7Dest $4371
.define rDMA7SourceOffsetW $4372
.define rDMA7SourceBank $4374
.define rDMA7ByteCountW $4375
